name: Meu Curriculo Deploy Hostgator

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Make ${{matrix.work}} ${{matrix.arch}}
    steps:
      - name: Checkout do repositorio
        uses: actions/checkout@v1
      - name: Deploy para meu hosting
        uses: MitchWind/ftp-deploy@master
        env:
            SSH_PRIVATE: ${{ secrets.SERVER_SSH_KEY }}
            ARGS: "-rltgoDzv0 --delete"
            SOURCE: "dist/"
            REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
            REMOTE_USER: ${{ secrets.REMOTE_USER }}
            REMOTE_PORT: ${{ secrets.REMOTE_PORT }}
            TARGET: ${{ secrets.REMOTE_TARGET }}
            